# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: AssetCooker.sln

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, DebugOpt, Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Generate Solution
      shell: cmd
      run: premake.bat

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Build
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{ matrix.config }} ${{env.SOLUTION_FILE_PATH}}

    # Skip the tests in Release
    - if: ${{ matrix.config != 'Release' }}
      shell: cmd
      run: .\bin\x64\${{ matrix.config }}\AssetCooker${{ matrix.config }}.exe -test

